apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tasks-app
  labels:
    app.kubernetes.io/name: tasks
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tasks
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
