apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: tasks-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-local-path
  resources:
    requests:
      storage: 5Gi
